version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-frases-dev
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    entrypoint:
      - ./init.sh
    networks:
      - network_local

  postgresql_local:
    build: docker/postgres/.
    env_file:
      - .env
    ports:
      - '5454:5432'
    networks:
      - network_local
    volumes:
      - pg_data_local:/var/lib/postgresql/data

volumes:
  pg_data_local:

networks:
  network_local:
    driver: bridge
