version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-frases-dev
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    entrypoint:
      - ./init.sh
    networks:
      - postgres-compose-network

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "PgAdmin#2023"
      POSTGRES_DB: "sistema-frases-dev"
    ports:
      - "15432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin#2023"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
