version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-frases-dev
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    entrypoint:
      - ./init.sh